run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - gofumpt
    - gci
    - goimports
    - govet
    - staticcheck
    - revive
    - errcheck
    - gocritic
    - ineffassign
    - unused
    - unparam
    - cyclop
    - loggercheck

linters-settings:
  gofmt:
    simplify: true
  gci:
    sections:
      - standard # Standard packages
      - default # Default section for all other imports
      - prefix(github.com/Nexlayer/nexlayer-cli) # Project-specific packages
  gofumpt:
    extra-rules: true # Enable extra rules for stricter formatting
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated
    disabled-checks:
      - commentFormatting
      - unnamedResult
  cyclop:
    max-complexity: 15
    package-average: 10.0
    skip-tests: true
  loggercheck:
    packages:
      - log
      - fmt
    not-allowed-functions:
      - log.Print
      - log.Printf
      - log.Println
      - fmt.Print
      - fmt.Printf
      - fmt.Println

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - cyclop
        - unparam

  max-same-issues: 50
  
  # Exclude specific issues
  exclude:
    - "should have comment"  # Exclude missing comment warnings for unexported symbols
    - "always receives"      # Exclude warnings about unused parameters in interfaces
    - "parameter .* is always"  # Exclude unparam warnings for interface implementations
