run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - tools

linters:
  enable-all: true
  disable:
    - exhaustivestruct  # deprecated
    - golint           # deprecated
    - ifshort         # deprecated
    - interfacer      # deprecated
    - maligned        # deprecated
    - nosnakecase     # deprecated
    - scopelint       # deprecated
    - structcheck     # deprecated
    - varcheck        # deprecated
    - deadcode        # deprecated
    - exhaustruct     # too strict
    - gci             # conflicts with gofmt
    - gofumpt         # conflicts with gofmt
    - lll             # line length is subjective
    - wsl             # too opinionated

linters-settings:
  govet:
    check-shadowing: true
  cyclop:
    max-complexity: 15
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 100
    statements: 50
  godox:
    keywords:
      - FIXME
      - BUG
      - TODO
  gofmt:
    simplify: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gomodguard:
    blocked:
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
            reason: "see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0
