run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - gofumpt
    - gci
    - goimports
    - govet
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  gci:
    sections:
      - standard # Standard packages
      - default # Default section for all other imports
      - prefix(github.com/Nexlayer/nexlayer-cli) # Project-specific packages
  gofumpt:
    extra-rules: true # Enable extra rules for stricter formatting

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  max-same-issues: 50
