blank_issues_enabled: false
contact_links:
  - name: Nexlayer Documentation
    url: https://docs.nexlayer.io/
    about: Check our documentation for answers to common questions
  - name: Community Discussions
    url: https://github.com/Nexlayer/nexlayer-cli/discussions
    about: Ask questions and discuss with other community members 