application:
  template:
    name: mongo-expres-next
    deploymentName: dgasdgg
    registryLogin:
      registry: ghcr.io
      username: dafdsa
      personalAccessToken: gjkhfk'
    pods:
    - type: database
      exposeHttp: false
      name: mongo
      tag: ghcr.io/dafdsa/ddffff-mongo:v0.0.1
      privateTag: true
      vars:
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: passw0rd
      - key: DB_NAME
        value: ddffff
    - type: backend
      exposeHttp: false
      name: expres
      tag: ghcr.io/dafdsa/ddffff-expres:v0.0.1
      privateTag: true
      vars:
      - key: DATABASE_URL
        value: DATABASE_CONNECTION_STRING
    - type: frontend
      exposeHttp: true
      name: next
      tag: ghcr.io/dafdsa/ddffff-next:v0.0.1
      privateTag: true
      vars:
      - key: BACKEND_URL
        value: BACKEND_CONNECTION_URL
