name: Go Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'
        cache: true
        
    - name: Get dependencies
      run: go mod download
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v -coverprofile=coverage.txt ./...
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
        fail_ci_if_error: false 